### ISSUE TITLE
how can we achieve the effect to thin nose 

### ISSUE THREAD

**Issue by pawaom** [DingProg/Makeup#2]
how can we achieve the effect to thin nose 

like this 
![Morphing](https://user-images.githubusercontent.com/28686824/71552220-b60e5700-2a1e-11ea-94d8-4a84b814c306.gif)

https://www.banuba.com/hubfs/Morphing.gif

**Comment by DingProg** [comment]
### 这个效果已经实现了，请参考瘦脸算法，但是需要人脸关键点才可以实现.

[SmallFaceUtils](https://github.com/DingProg/Makeup/blob/master/app/src/main/java/com/ding/makeup/beauty/SmallFaceUtils.java)

### 鼻子的算法，和瘦脸算法很相似、找到对应的关键点，拖动就可以。可以参考手动算法
[SmallFaceView](https://github.com/DingProg/Makeup/blob/master/app/src/main/java/com/ding/makeup/beauty/SmallFaceView.java)
